const API_BASE_URL = 'http://202.60.232.93:23333';
const POLL_INTERVAL = 10000;
const DEFAULT_WEEKLY_GOAL = 5;
const RECENT_PRACTICE_LIMIT = 60;
const PRACTICE_RECOMMENDATION_COUNT = 3;
const PRACTICE_TARGET_SCORE = 85;
const STABLE_PRACTICE_TARGET = 3;
const STABLE_SCORE_LINE = 80;

module.exports = {
  API_BASE_URL,
  POLL_INTERVAL,
  DEFAULT_WEEKLY_GOAL,
  RECENT_PRACTICE_LIMIT,
  PRACTICE_RECOMMENDATION_COUNT,
  PRACTICE_TARGET_SCORE,
  STABLE_PRACTICE_TARGET,
  STABLE_SCORE_LINE,
};
